name: Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t natalieaoya/flask.webapp:latest .
          docker push natalieaoya/flask.webapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind
        uses: helm/kind-action@v1
        with:
          version: v0.21.0

      - name: Create Kind cluster
        run: kind create cluster --name webapp

      - name: Load Docker image into Kind
        run: |
          kind load docker-image natalieaoya/flask.webapp:latest --name webapp

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s-deployment.yaml
          
      - name: Wait for deployment to complete
        run: |
          kubectl rollout status deployment/flask-app-deployment

      - name: Port-forward to access locally
        run: |
          kubectl port-forward deployment/flask-app-deployment 5000:5000 &
